### ISSUE TITLE
NerdTree cannot navigate into subdirs

### ISSUE THREAD

**Issue by Gys** [saturnism/go-ide#1]
I have the exact same problem as described here:
http://stackoverflow.com/questions/8753286/nerd-tree-enter-does-not-open-sub-dirs

I tried running the container on OSX 10.11.1 and Ubtuntu 14.04.3 - both with latest Docker version.

Strange, because in the screenshot part of your blog (https://medium.com/google-cloud/my-ide-in-a-container-49d4f177de) that problem does not seem to exist ? Because the subdirs there are shown correctly with a '+'-symbol.
So how could this be happening to my install ?

**Comment by booyaa** [comment]
Have you tried the suggested fix? adding this line to the `.vimrc` `let g:NERDTreeDirArrows=0`. This fixed it for me.

**Comment by Gys** [comment]
Sorry, no I did not because I already assumed the nerdtree - problem was solvable ;-)

My problem is that it seems the very same container works fine in one place (the authors machine in the screenshot) but not on my machine. That is not how I imagined this would work. The whole idea behind this container is having it working identical everywhere. No tweaks needed depending on when and where it is run.

**Comment by saturnism** [comment]
i actually just uploaded a new file and image
